version: '3.8'
services:
  service1:
    build:
      context: ./service_1
    container_name: service_1
    networks:
      - dpdzero-nt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3


  service2:
    build:
      context: ./service_2
    container_name: service_2
    networks:
      - dpdzero-nt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3


  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2
    networks:
      - dpdzero-nt
    volumes:
      - ./logs:/var/log/nginx

networks:
  dpdzero-nt:
    driver: bridge

