FROM python:3.12-slim AS builder
WORKDIR /app
RUN pip install uv
COPY . .
RUN uv sync --compile-bytecode

FROM python:3.12-alpine
WORKDIR /app
RUN apk add --no-cache curl
RUN pip install uv

COPY --from=builder /app /app
EXPOSE 8002
CMD ["uv", "run", "app.py"]

